import { Router } from 'express';
import { healthRouter } from './health.js';
import { recipesRouter } from './recipes.js';
import { authRouter } from './auth.js';
import { favoritesRouter } from './favorites.js';
import { pricesRouter } from './prices.js';
import { plannerRouter } from './planner.js';
import { preferencesRouter } from './preferences.js';
import { historyRouter } from './history.js';
import { recommendationsRouter } from './recommendations.js';
import { uploadsRouter } from './uploads.js';
import { challengesRouter } from './challenges.js';
import { adminRouter } from './admin.js';
import { adsRouter } from './ads.js';
import { billingRouter } from './billing.js';
import { profileRouter } from './profile.js';
 
export const router = Router();
 
router.use('/health', healthRouter);
router.use('/recipes', recipesRouter);
router.use('/auth', authRouter);
router.use('/favorites', favoritesRouter);
router.use('/prices', pricesRouter);
router.use('/planner', plannerRouter);
router.use('/preferences', preferencesRouter);
router.use('/history', historyRouter);
router.use('/recommendations', recommendationsRouter);
router.use('/uploads', uploadsRouter);
router.use('/challenges', challengesRouter);
router.use('/ads', adsRouter);
router.use('/billing', billingRouter);
router.use('/admin', adminRouter);
router.use('/profile', profileRouter);